let express= require("express")
let mongoose=   require('mongoose')
let bcryptjs=  require('bcryptjs')
let cors=require('cors')
let app=  express()
let User=  require('./db.js')
let jwt=  require('jsonwebtoken')
app.use(express.json())
app.use(cors())
